<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Ebook extends Model
{
    use HasFactory, HasUuids, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     *
     * Note: The 'slug' field is auto-generated by EbookObserver when the ebook is created.
     * It should not be set manually by the user or in the controller.
     * The observer generates a unique slug from the 'name' field automatically.
     */
    protected $fillable = [
        'name',
        'slug', // Auto-generated by EbookObserver
        'description',
        'category_id',
        'price',
        'file',
        'image',
        // Mautic fields
        'mautic_asset_id',
        'mautic_field_id',
        'mautic_field_alias',
        'mautic_email_id',
        'mautic_email_name',
        'mautic_campaign_id',
        'last_email_html',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'price' => 'decimal:2',
        ];
    }

    /**
     * Get the category that owns the ebook.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the image URL.
     */
    protected function imageUrl(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->image ? Storage::url($this->image) : null,
        );
    }

    /**
     * Get the purchases for the ebook.
     */
    public function purchases(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Purchase::class);
    }
}
