name: lint-autofix

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: lint-autofix-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  autofix:
    uses: ./.github/workflows/_lint-reusable.yml
    with:
      mode: fix
    secrets: inherit
